name: Update Release Tag for Single Repo

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

env:
  TARGET_REPO: yjsexam/lobe-chat
  SOURCE_REPO: lobehub/lobe-chat

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          token: ${{ secrets.PAT }}
          path: target-repo

      - name: Fetch Latest Release from Source Repository
        id: get-latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ env.SOURCE_REPO }}
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
        working-directory: target-repo

      - name: Create or Update Tag
        run: |
          TAG_NAME=${{ steps.get-latest-release.outputs.release }}
          git tag -f $TAG_NAME
          git push origin -f $TAG_NAME
        working-directory: target-repo

      - name: Fetch Release Notes from GitHub API
        id: get-release-notes
        run: |
          TAG_NAME=${{ steps.get-latest-release.outputs.release }}
          RELEASE_NOTES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ env.SOURCE_REPO }}/releases/tags/$TAG_NAME | jq -r '.body // "No release notes available"')
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create or Update GitHub Release
        run: |
          TAG_NAME=${{ steps.get-latest-release.outputs.release }}
          gh release create $TAG_NAME --title "$TAG_NAME" --notes "${{ env.RELEASE_NOTES }}" --target main || \
          gh release edit $TAG_NAME --title "$TAG_NAME" --notes "${{ env.RELEASE_NOTES }}" --target main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        working-directory: target-repo
